server:
  port: 8091
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: postgres
    password: "{cipher}AQBXPY2dwdp97YRNfAHaC+YIpvFubprLJV5BxLjimjDiVkWFIlJ1R3/BIuvLXAkD0Hoqdxe2WER+5i9AjH//KOxCzIwmp8DR45mGQ6jmS2u9tzcYaF49gSp1DefDw1eyY2SQldIDjeKYZjyslMzhxZLduLsBuJu0jWOcxrFakiZ8Q38PSOp8M/czy+JP4ioEhY2GjtNfSIC2gKSQqRD2rNWEQzH5J6J4MH4BbPkA4gcAqPQqSZzmesjzXJnBTZtV3QT+k7xumyNY8JmYauykI67N00bJEj7lhw1HzNbj5FknAQp4txwfbZhnd95HZFZC4+7uSwR9PR1p436XbRA1piqvK37VmiEUegnUK5l1W94l6oNsPacjrRYiivd7BLhAOaKW4PqYT8ZTq2bqABIeDpbZ"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: true
    show-sql: true
logging:
  level:
    com.example.orderservice: DEBUG