server:
  port: 8091
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: postgres
    password: "{cipher}AQC9enN+1OyGAK9hbNt+xA7MSJIMG5kcjev/YJQJ5QvQSLM6Pcg/nOrapqOimGx0WHbTDrgvhZyfSfFum4/evWgVyok80UnKBws3Dz5Xu5qxLiYASAE7R2tE4V8L3IuJDlFUzCOjY7Vg2JMEP92arID7am+jpAMpPgdGC2LLVNpqXDtBcNzjRMNlOmYpub3mkHd1IFwQCEWiD5sDCh4qGvxIC/SkAwUv4eSJ29UJ+U2rDRJ1jbdRRBEWyZzQzLMg9g9n4VP+l92gpWwndIdBvU9Ixd9wjp5OW+yuXI84ESvz2e2u2IurqBVxJQhx5ZYs6BOr0MvWjMgfs4uaAF8aIBFME/E2XsbqApJ6JCN8wUHA3o5YLZAzsG2NqlyKy03Glf0GSzauNDpi1jiDG3Iu9S3J"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: true
    show-sql: true
logging:
  level:
    com.example.orderservice: DEBUG